{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.gravityfield",
    "module": "gravity-sdk",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "gravity-sdk-1.0.2.aar",
          "url": "gravity-sdk-1.0.2.aar",
          "size": 1518755,
          "sha512": "951d5d42c70261a300b46f9d74bc699e2c960b30b876846c34e1f9c0096b7430d027fc2164c12de9eadf36816bf2bd0fbb637e33425040dfab3eb637767d3fcd",
          "sha256": "f60dbc18bcc77349554c24893ea63c01e490cb2ea67fe6c7972738b32a7eca62",
          "sha1": "07707a9aeffffd06e840b502f0a167b92ba84d91",
          "md5": "233975a60bdb85d711547709635a497a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-no-arg",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-okhttp",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "gravity-sdk-1.0.2.aar",
          "url": "gravity-sdk-1.0.2.aar",
          "size": 1518755,
          "sha512": "951d5d42c70261a300b46f9d74bc699e2c960b30b876846c34e1f9c0096b7430d027fc2164c12de9eadf36816bf2bd0fbb637e33425040dfab3eb637767d3fcd",
          "sha256": "f60dbc18bcc77349554c24893ea63c01e490cb2ea67fe6c7972738b32a7eca62",
          "sha1": "07707a9aeffffd06e840b502f0a167b92ba84d91",
          "md5": "233975a60bdb85d711547709635a497a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "gravity-sdk-1.0.2-sources.jar",
          "url": "gravity-sdk-1.0.2-sources.jar",
          "size": 116955,
          "sha512": "efa31afe40d85b9b02790e0020c28dd3344e32ecbb65b1eada972f20a5e11c660e82c2c2048935c952aee7dbfc4bd427c6f21158cf1d7222d6e94738830d5262",
          "sha256": "7bc0f49a388c25c8d9e81a931fdc54d0d880882a686ddc138ce44d7bc90c3707",
          "sha1": "21f554cbfed7a576d0d337d3e82e38b76cdb636d",
          "md5": "925ca11b535d890e731d7e28a1c36bd0"
        }
      ]
    }
  ]
}
