{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.gravityfield",
    "module": "gravity-sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "gravity-sdk-1.0.0.aar",
          "url": "gravity-sdk-1.0.0.aar",
          "size": 1492056,
          "sha512": "3db9aba1bf870f57d10ab21b6e77c65a00ad8742b7f514b8c740225d41e6fcd6c18de454dad7c0d414be4219ae79d9a562d670c52c57d0ee23a3ad9c625955db",
          "sha256": "614ab284e76713ec3c8e99e67e3ae380af2b80e0b2c9341aff79cc31f2f37e48",
          "sha1": "aeef8f181fecc5c00e3fd07cf0e619c7509ed717",
          "md5": "2b29ce6711779a0ee6d6722acb0e851a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-no-arg",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-okhttp",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "gravity-sdk-1.0.0.aar",
          "url": "gravity-sdk-1.0.0.aar",
          "size": 1492056,
          "sha512": "3db9aba1bf870f57d10ab21b6e77c65a00ad8742b7f514b8c740225d41e6fcd6c18de454dad7c0d414be4219ae79d9a562d670c52c57d0ee23a3ad9c625955db",
          "sha256": "614ab284e76713ec3c8e99e67e3ae380af2b80e0b2c9341aff79cc31f2f37e48",
          "sha1": "aeef8f181fecc5c00e3fd07cf0e619c7509ed717",
          "md5": "2b29ce6711779a0ee6d6722acb0e851a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "gravity-sdk-1.0.0-sources.jar",
          "url": "gravity-sdk-1.0.0-sources.jar",
          "size": 111225,
          "sha512": "6ed93659218ddf2c394c8a3600161bb31c00b558a3106d89f5228e890d235df2adb0bf5ac5408d67d43b32c275a312a483709bdbcae4946ec5c9ee0661efe03b",
          "sha256": "8a10bd4c46591269e6ccd61adb2e6076446285db6a19e4cc103d79632f723ee7",
          "sha1": "ba44e11707b1517a9785fb988b33ed0392efb6d3",
          "md5": "5baad1c1b89deebd75a9ce1496856f89"
        }
      ]
    }
  ]
}
