{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.gravityfield",
    "module": "gravity-sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "gravity-sdk-1.0.0.aar",
          "url": "gravity-sdk-1.0.0.aar",
          "size": 1625723,
          "sha512": "b43399bc7cdb7c3cbb08bb8fe948c0524ce1d0a9c04603bee7c66c20bd60f1d43958763e3942e81f2b23efef06705d41122f3f62cf212a28da2459d2fe0ce597",
          "sha256": "146a2831b1195b930929c9cb991f899b7c729a81439de9a7703ded2e3606df30",
          "sha1": "3209c48d0c7f82a380129ab2c842bef600f3d0ad",
          "md5": "00043d4fe43786a9225a59c59c338ddf"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.09.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-no-arg",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "gravity-sdk-1.0.0.aar",
          "url": "gravity-sdk-1.0.0.aar",
          "size": 1625723,
          "sha512": "b43399bc7cdb7c3cbb08bb8fe948c0524ce1d0a9c04603bee7c66c20bd60f1d43958763e3942e81f2b23efef06705d41122f3f62cf212a28da2459d2fe0ce597",
          "sha256": "146a2831b1195b930929c9cb991f899b7c729a81439de9a7703ded2e3606df30",
          "sha1": "3209c48d0c7f82a380129ab2c842bef600f3d0ad",
          "md5": "00043d4fe43786a9225a59c59c338ddf"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "gravity-sdk-1.0.0-sources.jar",
          "url": "gravity-sdk-1.0.0-sources.jar",
          "size": 109971,
          "sha512": "b3ec33a9ff5a33d451f2cb3eddc3dd9532573253b83d3b0591a6306ac9838f9c1253bd7b25cba85dd17e022c9dd64d82ded8aeaa8d96cdc597d38315910713d3",
          "sha256": "945c5117e7ef1d4427b46be32b48f42f859a5491fb020c221ee633bb93b9c8bb",
          "sha1": "beffc5d6c8f44864c0f33565878b29921b28d65d",
          "md5": "ec6c7e9832b20e4eaf418e31d3d1e9d4"
        }
      ]
    }
  ]
}
