{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.gravityfield",
    "module": "gravity-sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "gravity-sdk-1.0.0.aar",
          "url": "gravity-sdk-1.0.0.aar",
          "size": 1498579,
          "sha512": "a6426eea92b6ce2e8279e5eedf8675bbfbf6351c31e2a590c2b3cb24157ef447182e2827a19a5be674e0a4d03b99ad965788792c777deff4b7aa7d830fccc6bf",
          "sha256": "997ee3519efd9d7c39ef77eec2345307fe21e4e4bd663a3647d8fa2cadbde47c",
          "sha1": "c6a6c1db2a825d413af5b32cc1d540a4f7eff0b0",
          "md5": "4b79400aacf43ff41a7a2fb4defcea5a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-no-arg",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-okhttp",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "gravity-sdk-1.0.0.aar",
          "url": "gravity-sdk-1.0.0.aar",
          "size": 1498579,
          "sha512": "a6426eea92b6ce2e8279e5eedf8675bbfbf6351c31e2a590c2b3cb24157ef447182e2827a19a5be674e0a4d03b99ad965788792c777deff4b7aa7d830fccc6bf",
          "sha256": "997ee3519efd9d7c39ef77eec2345307fe21e4e4bd663a3647d8fa2cadbde47c",
          "sha1": "c6a6c1db2a825d413af5b32cc1d540a4f7eff0b0",
          "md5": "4b79400aacf43ff41a7a2fb4defcea5a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "gravity-sdk-1.0.0-sources.jar",
          "url": "gravity-sdk-1.0.0-sources.jar",
          "size": 113281,
          "sha512": "710363ec7b5680e64e5705230638e8e42b5224583f355eb40271a0dcb571b6ad123f9281e531df96ed9bd1aa8fb28dc6cb369a534ecfa27344c390921da6c794",
          "sha256": "19c835f546eb114bced2a4e77707d1840cbacf9b3105393cf83ca88ad228e183",
          "sha1": "c4b6cee7d67178c0009bd2a717dd5c75024a5cdb",
          "md5": "0600b2c8138c8c03bd17c377c680bb2e"
        }
      ]
    }
  ]
}
