{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.gravityfield",
    "module": "gravity-sdk",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "gravity-sdk-1.0.1.aar",
          "url": "gravity-sdk-1.0.1.aar",
          "size": 1518912,
          "sha512": "9f04c5b3821db206e680ed8e2541b4badb3f40a728bea439e84746efdd56852acec767463b8543ff29f7f3a1f1a16348645ccb565c5aab77fc12bd7d24f2ff7e",
          "sha256": "61bb3d523114d89e32230d7910c14270274734d8da4068381c9db7b24952b4be",
          "sha1": "ae244504909750086e3a2755f497deeadc20cefc",
          "md5": "5ee007a146f06e0dfcf0a0d8eeb594f6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-no-arg",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-okhttp",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "gravity-sdk-1.0.1.aar",
          "url": "gravity-sdk-1.0.1.aar",
          "size": 1518912,
          "sha512": "9f04c5b3821db206e680ed8e2541b4badb3f40a728bea439e84746efdd56852acec767463b8543ff29f7f3a1f1a16348645ccb565c5aab77fc12bd7d24f2ff7e",
          "sha256": "61bb3d523114d89e32230d7910c14270274734d8da4068381c9db7b24952b4be",
          "sha1": "ae244504909750086e3a2755f497deeadc20cefc",
          "md5": "5ee007a146f06e0dfcf0a0d8eeb594f6"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "gravity-sdk-1.0.1-sources.jar",
          "url": "gravity-sdk-1.0.1-sources.jar",
          "size": 116949,
          "sha512": "b31cbb55c07481610d29d925a06faae4b0b9d935d476182b9a24d0a24fa52adad7823b1bcc5c580f8c923412559061505bd6c7a4481cb93b5a0a197150469477",
          "sha256": "115da9499bd1a7e935919e675f71b1337cfc2ed23d5d164da8398be60f4d4acd",
          "sha1": "051912338f3c2bd30d5b1403bda4f78b19c3c79b",
          "md5": "0df0d95d8d8126ccebdfd84d96d1c4d4"
        }
      ]
    }
  ]
}
